"$schema" = 'https://starship.rs/config-schema.json'

format = """
$jobs\
$cmd_duration\
$localip\
$sudo\
$username\
$directory\
$git_branch\
$git_status\
$c\
$dart\
$deno\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$java\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$python\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$vlang\
$zig\
$aws\
$azure\
$gcloud\
$openstack\
$buf\
$docker_context\
$nix_shell\
$terraform\
$direnv\
$line_break\
$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#83a598'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[cmd_duration]
format = "[ $duration ]()"

[jobs]
symbol = " "
format = "[$symbol$number ]()"

[localip]
ssh_only = true
format = " [$localipv4 ]()"
disabled = false

[sudo]
disabled = false
symbol = "󱦄 "
format = "[$symbol](fg:color_purple)"

[username]
disabled = false
show_always = false
format = '[$user ](bold fg:color_purple)'

[directory]
home_symbol = " "
read_only = "󰌾"
format = "[$path](fg:color_yellow)"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = " …/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = " "
format = ' on [$symbol $branch](fg:color_aqua)'

[git_status]
format = '[($all_status$ahead_behind)](fg:color_aqua)'

[c]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[dart]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[deno]
symbol = "∫"
format = ' via [$symbol( $version)](fg:color_orange)'

[elixir]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[elm]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[erlang]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[golang]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[gradle]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[haskell]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[java]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[kotlin]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[lua]
version_format = "${raw}"
symbol = "󰢱"
format = ' via [$symbol( $version)](fg:color_orange)'

[nim]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[nodejs]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[ocaml]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[perl]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[php]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[python]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[rlang]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[ruby]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[rust]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[scala]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[swift]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[vlang]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[zig]
symbol = ""
format = ' via [$symbol( $version)](fg:color_orange)'

[aws]
symbol = "󰸏"
format = ' / [$symbol( $profile)](fg:color_orange)'

[azure]
symbol = ""
format = ' / [$symbol( $subscription)](fg:color_orange)'

[gcloud]
symbol = "󱇶"
format = ' / [$symbol( $account(@$domain))](fg:color_orange)'

[openstack]
symbol = "■"
format = ' / [$symbol( $cloud(\($project\)))](fg:color_orange)'

[buf]
symbol = "■"
format = ' / [$symbol( $version $buf_version)](fg:color_orange)'

[docker_context]
symbol = ""
format = ' / [$symbol( $context) ](fg:color_blue)'

[nix_shell]
disabled = false
symbol = ""
impure_msg = '[⌽](bold fg:color_blue)'
pure_msg = '[⌾](bold fg:color_blue)'
unknown_msg = '[◌](bold fg:color_yellow)'
format = ' / [$symbol $state](bold fg:color_blue)'

[terraform]
symbol = ""
format = ' / [$symbol( $context) ](fg:color_blue)'

[direnv]
disabled = false
allowed_msg = ""
not_allowed_msg = " !"
format = ' / [$allowed ](fg:color_green)'

[time]
disabled = false
time_format = "%R"
format = '[   $time](fg:color_bg1)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[󰞷](bold fg:color_green)'
error_symbol = '[󰞷](bold fg:color_red)'
vimcmd_symbol = '[󱊷](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
