{ pkgs, gitDirectory, ... }:
{
  enable = true;
  clock24 = true;
  customPaneNavigationAndResize = true;
  escapeTime = 10;
  keyMode = "vi";
  mouse = true;
  terminal = "screen-256color";
  extraConfig = ''
    set -g xterm-keys on
    set -g set-clipboard on
    set -g extended-keys on
    set -g extended-keys-format csi-u
    set-option -g status-interval 3
    set-option -g status-position top
    set-option -ga terminal-overrides ",xterm-256color:Tc"
    bind c new-window -c '#{pane_current_path}'
    bind v split-window -h -c '#{pane_current_path}'
    bind s split-window -v -c '#{pane_current_path}'
    bind-key -n C-h send-keys \u007f

    set-option -gq status-justify left
    set-option -gq status-left-style none
    set-option -gq status-left-length 80
    set-option -gq status-right-style none
    set-option -gq status-right-length 80
    set-window-option -gq window-status-separator ""
    set-option -gq status-right ""

    # Theme colors (generated by tools/change-theme/run.sh)
    source-file -q "${gitDirectory}/dotfiles/config/tmux/theme.conf"
  '';
}
