set-option -gq status-style "bg=default fg=#5e5252"
set-option -gq window-status-style "bg=default fg=#5e5252"
set-option -gq window-status-activity-style "bg=default fg=#5e5252"
set-option -gq window-status-current-style "bg=default fg=#5e5252"
set-option -gq pane-active-border-style "fg=#5e5252"
set-option -gq pane-border-style "fg=#5e5252"
set-option -gq message-style "bg=default fg=#5e5252"
set-option -gq message-command-style "bg=default fg=#5e5252"
set-option -gq display-panes-active-colour "#5e5252"
set-option -gq display-panes-colour "#5e5252"
set-option -gq clock-mode-colour "#426a79"
set-window-option -gq window-status-bell-style "bg=default fg=#be100e"
set-option -gq status-left "#[bg=default,fg=#5e5252] #S"
set-window-option -gq window-status-current-format "#[bg=default,fg=#d08b30,nobold,noitalics,nounderscore] 󰍹 "
set-window-option -gq window-status-format "#[bg=default,fg=#5e5252,nobold,noitalics,nounderscore] 󰍹 "
