set-option -gq status-style "bg=default fg=#5e5252"
set-option -gq window-status-style "bg=default fg=#5e5252"
set-option -gq window-status-activity-style "bg=default fg=#5e5252"
set-option -gq window-status-current-style "bg=default fg=#5e5252"
set-option -gq pane-active-border-style "fg=#5e5252"
set-option -gq pane-border-style "fg=#5e5252"
set-option -gq message-style "bg=default fg=#5e5252"
set-option -gq message-command-style "bg=default fg=#5e5252"
set-option -gq display-panes-active-colour "#5e5252"
set-option -gq display-panes-colour "#5e5252"
set-option -gq clock-mode-colour "#3a6980"
set-window-option -gq window-status-bell-style "bg=default fg=#a4302a"
set-option -gq status-left "#[bg=default,fg=#5e5252] #S"
set-window-option -gq window-status-current-format "#[bg=default,fg=#ab6a10,nobold,noitalics,nounderscore] 󰍹 "
set-window-option -gq window-status-format "#[bg=default,fg=#5e5252,nobold,noitalics,nounderscore] 󰍹 "
