set-option -gq status-style "bg=default fg=#837a72"
set-option -gq window-status-style "bg=default fg=#837a72"
set-option -gq window-status-activity-style "bg=default fg=#837a72"
set-option -gq window-status-current-style "bg=default fg=#837a72"
set-option -gq pane-active-border-style "fg=#837a72"
set-option -gq pane-border-style "fg=#837a72"
set-option -gq message-style "bg=default fg=#837a72"
set-option -gq message-command-style "bg=default fg=#837a72"
set-option -gq display-panes-active-colour "#837a72"
set-option -gq display-panes-colour "#837a72"
set-option -gq clock-mode-colour "#2848a9"
set-window-option -gq window-status-bell-style "bg=default fg=#a5222f"
set-option -gq status-left "#[bg=default,fg=#837a72] #S"
set-window-option -gq window-status-current-format "#[bg=default,fg=#ac5402,nobold,noitalics,nounderscore] 󰍹 "
set-window-option -gq window-status-format "#[bg=default,fg=#837a72,nobold,noitalics,nounderscore] 󰍹 "
