set-option -gq status-style "bg=default fg=#928374"
set-option -gq window-status-style "bg=default fg=#928374"
set-option -gq window-status-activity-style "bg=default fg=#928374"
set-option -gq window-status-current-style "bg=default fg=#928374"
set-option -gq pane-active-border-style "fg=#928374"
set-option -gq pane-border-style "fg=#928374"
set-option -gq message-style "bg=default fg=#928374"
set-option -gq message-command-style "bg=default fg=#928374"
set-option -gq display-panes-active-colour "#928374"
set-option -gq display-panes-colour "#928374"
set-option -gq clock-mode-colour "#83a598"
set-window-option -gq window-status-bell-style "bg=default fg=#fb4934"
set-option -gq status-left "#[bg=default,fg=#928374] #S"
set-window-option -gq window-status-current-format "#[bg=default,fg=#fabd2f,nobold,noitalics,nounderscore] 󰍹 "
set-window-option -gq window-status-format "#[bg=default,fg=#928374,nobold,noitalics,nounderscore] 󰍹 "
